name = "aoc25"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
simplifile = ">= 2.3.1 and < 3.0.0"
gleam_community_maths = ">= 2.0.0 and < 3.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gtempo = ">= 7.2.2 and < 8.0.0"
gleamy_structures = ">= 1.2.0 and < 2.0.0"
nibble = ">= 1.1.4 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
